# Generated by Django 3.2.7 on 2021-09-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
                ('img', models.ImageField(null=True, upload_to='profile/')),
                ('title', models.CharField(max_length=150, null=True)),
                ('intro', models.TextField()),
                ('bday', models.DateField()),
                ('website', models.CharField(max_length=150, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('degree', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('freelance', models.CharField(max_length=100)),
                ('long_description', models.TextField()),
            ],
        ),
    ]
