# Generated by Django 3.2.7 on 2021-09-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_fact'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fact',
            name='description',
        ),
    ]
