# Generated by Django 3.2.7 on 2021-09-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210917_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
