# Generated by Django 3.2.7 on 2021-09-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_experience_experiencedetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='duty',
        ),
        migrations.AddField(
            model_name='experience',
            name='duty',
            field=models.ManyToManyField(to='main.ExperienceDEtail'),
        ),
    ]
