# Generated by Django 3.2.7 on 2021-09-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210918_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='githublink',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
