# Generated by Django 3.2.7 on 2021-09-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210918_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_name', models.CharField(blank=True, max_length=250, null=True)),
                ('cert_date', models.CharField(blank=True, max_length=250, null=True)),
                ('college', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
