# Generated by Django 3.2.7 on 2021-09-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210918_1342'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collge',
            new_name='College',
        ),
    ]
