# Generated by Django 3.2.7 on 2021-09-19 03:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
